# Generated by Django 6.0.5 on 2026-05-20 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Rewards",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "action",
                    models.CharField(
                        help_text="Введите название привычки/вознаграждения",
                        max_length=100,
                        verbose_name="Название привычки/вознаграждения",
                    ),
                ),
                (
                    "is_habit",
                    models.BooleanField(
                        default=False,
                        help_text="Укажите признак приятной привычки",
                        verbose_name="Признак приятной привычки",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Habits",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "habit",
                    models.CharField(
                        help_text="Введите название привычки", max_length=100, verbose_name="Название привычки"
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        help_text="Введите место привычки", max_length=100, verbose_name="Место привычки"
                    ),
                ),
                (
                    "time_habit",
                    models.DateTimeField(help_text="Введите время привычки", verbose_name="Время привычки"),
                ),
                (
                    "time_complete",
                    models.PositiveIntegerField(
                        default=120,
                        help_text="Введите время на выполнение привычки в секундах",
                        verbose_name="Время на выполнение привычки в секундах",
                    ),
                ),
                (
                    "periodicity",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Введите периодичность привычки в днях",
                        verbose_name="Периодичность привычки в днях",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False, help_text="Укажите публичность привычки", verbose_name="Публичность привычки"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="Владелец привычки",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="habits_owner",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец привычки",
                    ),
                ),
                (
                    "related_habit",
                    models.ForeignKey(
                        help_text="Укажите связанную привычку",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="related_habit",
                        to="kurs5.rewards",
                        verbose_name="Связанная привычка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
                "ordering": ["habit"],
            },
        ),
    ]
