# Generated by Django 6.0.5 on 2026-05-23 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kurs5", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rewards",
            options={
                "ordering": ["action"],
                "verbose_name": "Вознаграждение",
                "verbose_name_plural": "Вознаграждения",
            },
        ),
        migrations.AddField(
            model_name="rewards",
            name="owner",
            field=models.ForeignKey(
                default=4,
                help_text="Укажите владельца вознаглаждения",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец вознаграждения",
            ),
            preserve_default=False,
        ),
    ]
