# Generated by Django 6.0.5 on 2026-05-23 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kurs5", "0002_alter_rewards_options_rewards_owner"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="habits",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Владелец привычки",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="habits_owner",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец привычки",
            ),
        ),
        migrations.AlterField(
            model_name="rewards",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Укажите владельца вознаглаждения",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец вознаграждения",
            ),
        ),
    ]
