# Generated by Django 6.0.5 on 2026-05-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kurs5", "0003_alter_habits_owner_alter_rewards_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habits",
            name="time_complete",
            field=models.PositiveIntegerField(
                default=120,
                help_text="Введите время на выполнение привычки в секундах",
                max_length=120,
                verbose_name="Время на выполнение привычки в секундах",
            ),
        ),
    ]
