# Generated by Django 6.0.5 on 2026-05-23 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kurs5", "0004_alter_habits_time_complete"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habits",
            name="periodicity",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Введите периодичность привычки в днях",
                max_length=7,
                verbose_name="Периодичность привычки в днях",
            ),
        ),
    ]
