# Generated by Django 6.0.5 on 2026-05-23 11:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kurs5", "0005_alter_habits_periodicity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habits",
            name="periodicity",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Введите периодичность привычки в днях",
                validators=[
                    django.core.validators.MinValueValidator(1, message="Значение не может быть меньше 1"),
                    django.core.validators.MaxValueValidator(7, message="Значение не может быть больше 7"),
                ],
                verbose_name="Периодичность привычки в днях",
            ),
        ),
        migrations.AlterField(
            model_name="habits",
            name="time_complete",
            field=models.PositiveIntegerField(
                default=120,
                help_text="Введите время на выполнение привычки в секундах",
                validators=[
                    django.core.validators.MinValueValidator(1, message="Значение не может быть меньше 1"),
                    django.core.validators.MaxValueValidator(120, message="Значение не может быть больше 100"),
                ],
                verbose_name="Время на выполнение привычки в секундах",
            ),
        ),
    ]
