name: Django CI/CD Pipeline

on:   # [push, pull_request]
  push:
    branches:
      - Feature/Kurs

  pull_request:
    branches:
      - Develop

jobs:
  test:
    runs-on: ubuntu-latest
    # needs: lint
    env:
      PYTHONPATH: $PWD
    # Тут можно указать раздел env: и задать переменные из секретов
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: ${{ secrets.DB_USER }}  # Тут можно указать либо из раздела выше ${{ env.ПЕРЕМЕННАЯ }}, либо грузим из секретов
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
          POSTGRES_DB: ${{ secrets.DB_NAME }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:7
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Check out code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Загружаем всю историю
        ref: main       # Явно указываем ветку

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libpq-dev file

    - name: Install Poetry
      run: pipx install poetry

    - name: Configure Poetry
      run: |
        poetry config virtualenvs.in-project true

    - name: Install dependencies
      run: |
        poetry install --no-interaction --no-root -n --without dev

    - name: Cache Poetry dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pypoetry
        key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}-v2
        restore-keys: |
          ${{ runner.os }}-poetry-

#    - name: Set environment variables
#      run: |  # Вполне возможно это и не надо будет если будет задан выше раздел env
#        echo "SECRET_KEY=django-insecure-ci-test-key" >> $GITHUB_ENV
#        echo "STRIPE_SECRET_KEY=sk_test_ci_dummy_key" >> $GITHUB_ENV
#        echo "DB_NAME=lms" >> $GITHUB_ENV
#        echo "DB_USER=postgres" >> $GITHUB_ENV
#        echo "DB_PASSWORD=postgres" >> $GITHUB_ENV
#        echo "DB_HOST=localhost" >> $GITHUB_ENV
#        echo "DB_PORT=5432" >> $GITHUB_ENV
#        echo "EMAIL_HOST_USER=test@example.com" >> $GITHUB_ENV
#        echo "EMAIL_HOST_PASSWORD=test_password" >> $GITHUB_ENV
#        echo "CELERY_BROKER_URL=redis://localhost:6379/0" >> $GITHUB_ENV
#        echo "CELERY_RESULT_BACKEND=redis://localhost:6379/0" >> $GITHUB_ENV
#        echo "REDIS_HOST=localhost" >> $GITHUB_ENV
#        echo "GITHUB_ACTIONS=true" >> $GITHUB_ENV

#    - name: Set Python path
#      run: |
#        echo "PYTHONPATH=$PWD" >> $GITHUB_ENV

    - name: Run migrations
      run: |
        export PYTHONPATH=$PWD
        poetry run python manage.py migrate

    - name: Run tests
      run: |
        export PYTHONPATH=$PWD
        poetry run python manage.py test 
