name: Django CI/CD Pipeline

on:   # [push, pull_request]
  push:
    branches:
      - Feature/Kurs

  pull_request:
    branches:
      - Develop

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Configure Poetry
        run: |
          poetry config virtualenvs.create true
          poetry config virtualenvs.in-project true

      - name: Cache Poetry dependencies
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
            venv-${{ runner.os }}-

      - name: Install dependencies
        run: |
          poetry install --no-interaction --no-root

      - name: Run linters
        run: |
          poetry run flake8 kurs5
          poetry run flake8 users
